version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Entered the build phase ...
      
      
artifacts:
  files:
    - /buildspec.yaml
        
      

      
